spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/vblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lu6218959?
upload:
  path:
    static: /cmd/
    real: D://cmd//